### ISSUE TITLE
Trying to get a config by file Warning: no config file was found issue

### ISSUE THREAD

**Issue by rodpacker** [TheJoin95/500px-bot#2]
Hola,

thx a lot for this script :) really appreciated.

When I try to run it it says:

"Trying to get a config by file
Warning: no config file was found
Logggin in
error page"

I have the config.json right next to it, just as it extracted and amended that file with username and password

thank you for your help

**Comment by rodpacker** [comment]
Hi,

is my question too simple or is this not getting supported anymore?

thanks

**Comment by TheJoin95** [comment]
Hi @rodpacker, 

I'm sorry for my late answer, pardon :|
I'm still working on this project and I will update this repo soon, with some new features, a doc and a better code quality. Can you wait for me? C:

Anywany, you need to make this question, because there is no doc or example here (my bad)!

By the way, actually to run the script you need to specifiy the config file with `--config config.json` and you need to make sure that in config.json there is an object like this:
```
"paramsLogin": {
            'authenticity_token': '',
            'session[email]': '',
            'session[password]': ''
        }
```

But I suggest you to wait for another "release", you can watch this repo for any future update ;)

**Comment by rodpacker** [comment]
Hi @TheJoin95 ,

awesome, thanks for your reply and sharing all of this.

Of course I can wait.  (I will try ur suggestions though as well)

Do you have an ETA on when these changes will be released by any chance mate?

**Comment by rodpacker** [comment]
Hi @TheJoin95 

sorry mate, I am a total python n00b, so please forgive my stupid questions.

so I went ahead and added --config config.json in run.py. when I get:
ile "/home/usr/Desktop/500px-bot-master/run.py", line 18
    --config config.json
                  ^
SyntaxError: invalid syntax

what exactly do I need to add where for the script to call the .json config file


thanx a lot for ur help mate

**Comment by TheJoin95** [comment]
@rodpacker hi, you don't need to put `--config config.json` in the run.py file, but in the terminal when you execute the script.

By the way, I've made some update, and I will update something more pretty soon so.. stay tuned.
I'm trying to do a better version, with more filter and options but it needs time :call_me_hand: 

Watch this repo,
thank you for your support ;)
